In [2]:
import numpy as np

In [1]:
#Задача 1
#Придумайте матрицы, которые обладают следующими свойствами:


In [22]:
# Диагональная, ортоганальная матрица
A = np.diag([7,-5,-2])
print(A)


[[ 7  0  0]
 [ 0 -5  0]
 [ 0  0 -2]]


In [42]:
A = np.array([[4,0,0], [0,4,0],[0,0,-4]])
AT = A.transpose()
ORT=A.dot(AT)
print(ORT)
#вынесем коэффициент = 16 и получим единичную матрицу

[[16  0  0]
 [ 0 16  0]
 [ 0  0 16]]


In [112]:
# нижнетреугольная, ортогональная матрица
A = np.tril([[1,2,3],[4,5,6],[7,8,9]], -1)
print(A)
#A = np.array([[1,0], [1,1]])
#A


[[0 0 0]
 [4 0 0]
 [7 8 0]]


In [113]:
AT = A.transpose()
AT

array([[0, 4, 7],
       [0, 0, 8],
       [0, 0, 0]])

In [126]:
ORT=A.dot(AT)


In [120]:
# нижнетреугольная, ортогональная матрица
n, m = 3, 5
H = np.random.rand(n, m)
u, s, vh = np.linalg.svd(H, full_matrices=False)
mat = u @ vh

print(mat @ mat.T) # -> eye(n)

[[1.00000000e+00 8.32667268e-17 0.00000000e+00]
 [8.32667268e-17 1.00000000e+00 1.38777878e-16]
 [0.00000000e+00 1.38777878e-16 1.00000000e+00]]


In [121]:
A = np.triu(mat, -1)
print(A)

[[ 0.8327673  -0.43002171  0.11794573  0.2866199   0.15974289]
 [ 0.05619137  0.55709282  0.60653746  0.11497007  0.55261589]
 [ 0.          0.50791189 -0.29198185  0.718522   -0.35366682]]


In [118]:
AT = A.transpose()
E=A.dot(AT)

In [119]:
print(E)

[[ 1.          0.         -0.08099408]
 [ 0.          1.          0.01403967]
 [-0.08099408  0.01403967  0.98934897]]


In [122]:
# верхнеугольная ортогональная матрица
#создаем произвольную ортогональную матрицу.
n, m = 3, 5
H = np.random.rand(n, m)
u, s, vh = np.linalg.svd(H, full_matrices=False)
mat = u @ vh

print(mat @ mat.T) # -> eye(n)

[[ 1.00000000e+00  0.00000000e+00 -2.63677968e-16]
 [ 0.00000000e+00  1.00000000e+00  5.55111512e-17]
 [-2.63677968e-16  5.55111512e-17  1.00000000e+00]]


In [123]:
A = np.triu(mat, 0)
print(A)

[[-0.16460706  0.32610048  0.19265234  0.75298865 -0.51230476]
 [ 0.         -0.068765    0.49341032  0.38488839  0.75975039]
 [ 0.          0.          0.14664042 -0.0097153   0.13298998]]


In [125]:
AT = A.transpose()
E=A.dot(AT)
print(E)

[[ 1.         -0.0267748  -0.04719629]
 [-0.0267748   0.9735421   0.16965378]
 [-0.04719629  0.16965378  0.03928414]]


In [24]:
# матрица, у которой определитель = 1, и все элементы не равны 0
A = np.array([[1,2], [1,3]])
A

array([[1, 2],
       [1, 3]])

In [27]:
det = np.linalg.det(A)
print(det)

1.0


In [33]:
# матрица (3x3), у которой определитель = 1
A = [
[2, 0, 1],
[1, -1, 0],
[0, 3, 1]
]
det = np.linalg.det(A)
print(det)

1.0


In [99]:
# Найдите собственные значения и собственные вектора матриц:
m = np.array([[2, 2],
              [1, 3]])
print(m)

[[2 2]
 [1 3]]


In [100]:
A = np.array([[2, 2], [1, 3]])
w, v = np.linalg.eig(A)
print(A)

[[2 2]
 [1 3]]


In [101]:
for i in range(len(w)):
    print("Собственное значение " + str(w[i]))
    print("соответствующий ему собственный вектор " + str(v[:,i]))

Собственное значение 1.0
соответствующий ему собственный вектор [-0.89442719  0.4472136 ]
Собственное значение 4.0
соответствующий ему собственный вектор [-0.70710678 -0.70710678]
