In [13]:
#Посчитайте значение первой и второй производной функции:
#В точке x = 1.
import numpy as np
from scipy.optimize import approx_fprime


In [24]:
x = np.array([1, 2], dtype=np.float)
c1, c2, c3 = (2,7,1)

In [ ]:
# частные производные функции f(x,y)=2x^2y^3 + 1/x + y^2x + 7, 
#и для этой функции также градиент в точке (1,2)
def func(x, c1, c2, c3):
    "Coordinate vector `x` should be an array of size two."
    return c1 * x[0]**2*x[1]**3 + c3/x[0] + x[1]**2*x[0]**2+c3


In [25]:
# градиент
j = np.gradient(x)
print(j)

[1. 1.]


In [28]:
def func(x, c1, c2, c3):
    "Coordinate vector `x` should be an array of size two."
    return c1 * x[0]**2*x[1]**3 + c3/x[0] + x[1]**2*x[0]**2+c3


In [29]:
x = np.ones(2)
c1, c2, c3 = (2,7,1)
eps = np.sqrt(np.finfo(float).eps)
approx_fprime(x, func, [eps, eps], c1, c2, c3)

array([5.00000006, 8.00000012])

In [ ]:
#частная производная
#Fx=4*x*y**3-1/x**2+2*y*x
#Fy=2*x**2*3*y**2+2*y*x**2
x = np.array([1, 2], dtype=np.float)
c1, c2, c3 = (2, 2, 1)


In [34]:
# производная по x
def func(x, c1, c2, c3):
    "Coordinate vector `x` should be an array of size two."
    return c1 * x[0]*x[1]**3 - c3/x[0]**2 + c2*x[0]*x[1]**2


In [35]:
x = np.ones(2)
c1, c2, c3 = (2,2,1)
eps = np.sqrt(np.finfo(float).eps)
approx_fprime(x, func, [eps, eps], c1, c2, c3)

array([ 5.99999994, 10.00000012])

In [38]:
# производная по y
def func(x, c1, c2, c3):
    "Coordinate vector `x` should be an array of size two."
    return c1 * x[0]**2*c2*x[1]**2 + c3*x[0]**2*x[1]

In [39]:
x = np.ones(2)
c1, c2, c3 = (2,3,2)
eps = np.sqrt(np.finfo(float).eps)
approx_fprime(x, func, [eps, eps], c1, c2, c3)

array([16.00000012, 14.00000012])

In [41]:
# частные производные функции f(x,y)=x^2y - sin(xy) + cos(x^2) + 6y
#Fx=2*x*y-ycos(xy)-sin(x**2)*2*x
#Fy=x**2-x*cos(x*y)-sin(x**2)+6
x = np.array([1, 2], dtype=np.float)
c1, c2 = (2, 2)

In [42]:
#производная по x
def func(x, c1, c2):
    "Coordinate vector `x` should be an array of size two."
    return c1 * x[0]*x[1] -x[1]*np.cos(x[0]*x[1])- c2*x[0]* np.sin(x[0]**2)

In [43]:
x = np.ones(2)
c1, c2 = (2,2)
eps = np.sqrt(np.finfo(float).eps)
approx_fprime(x, func, [eps, eps], c1, c2)

array([-1.00268021,  2.30116871])

In [44]:
# производная по y
def func(x, c1):
    "Coordinate vector `x` should be an array of size two."
    return x[0]**2 -x[0]*np.cos(x[0]*x[1])- np.sin(x[0]**2)+c1

In [45]:
x = np.ones(2)
c1 = 2
eps = np.sqrt(np.finfo(float).eps)
approx_fprime(x, func, [eps, eps], c1)

array([1.2205641 , 0.84147099])